apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{.Values.app }}
    name: {{.Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{.Values.app }}
  template:
    metadata:
      labels:
        app: {{.Values.app }}
        name: {{.Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: webserver
              containerPort: {{ .Values.port }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: webserver
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: webserver
            initialDelaySeconds: 30
            periodSeconds: 3
          env:
            - name: SERVER_PORT
              value: !!integer {{ .Values.port }}
