
# Configuration file for the Federated Learning project with PlantVillage dataset.
#
# Includes:
#   - path of the original PlantVillage dataset and the target path for the split subsets,
#   - List of the crop images categories to use,
#   - Distributions between the subsets for each categories,
#   - Hyperparameters for training the models,
#   - Number of workers to use.
#
# Path for the various datasets:
# Original dataset:
#     Original PlantVillage dataset, as downloaded from source.
#     "PlantVillageData/dataset/"+data_type, i.e. "color"
# Output dataset:
#     Target path for the validation, test and workers subsets.
#     "PlantVillageData/dataset/dataset/processed/""
orig_dataset:
  path: /home/ubuntu/code/PlantVillage-Dataset/raw/color/
output_dataset:
  path: /home/ubuntu/code/PlantVillageData/dataset/processed/
  val_path: /home/ubuntu/code/PlantVillageData/dataset/processed/val/
  test_path: /home/ubuntu/code/PlantVillageData/dataset/processed/test/
  train_path: /home/ubuntu/code/PlantVillageData/dataset/processed/train



# List of categories available and categories to include to the analysis.
# categories: list
#     List of categories available in the dataset.
# included_categories: list
#     List of categories to include to the analysis.

categories: ['Soybean___healthy', 'Tomato___Tomato_mosaic_virus', 'Cherry_(including_sour)___healthy',
            'Strawberry___Leaf_scorch', 'Tomato___Spider_mites Two-spotted_spider_mite',
            'Pepper,_bell___Bacterial_spot', 'Tomato___Bacterial_spot', 'Apple___Apple_scab',
            'Potato___Early_blight', 'Tomato___Late_blight', 'Raspberry___healthy',
            'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot', 'Corn_(maize)___Northern_Leaf_Blight',
            'Corn_(maize)___Common_rust_', 'Grape___Esca_(Black_Measles)',
            'Cherry_(including_sour)___Powdery_mildew', 'Apple___Black_rot', 'Corn_(maize)___healthy',
            'Tomato___Target_Spot', 'Orange___Haunglongbing_(Citrus_greening)',
            'Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'Squash___Powdery_mildew',
            'Apple___Cedar_apple_rust', 'Grape___healthy', 'Apple___healthy', 'Tomato___Leaf_Mold',
            'Peach___Bacterial_spot', 'Tomato___Early_blight', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
            'Peach___healthy', 'Blueberry___healthy', 'Potato___Late_blight', 'Pepper,_bell___healthy',
            'Grape___Black_rot', 'Tomato___healthy', 'Potato___healthy', 'Strawberry___healthy',
            'Tomato___Septoria_leaf_spot']
included_categories: ['Strawberry___Leaf_scorch','Tomato___Bacterial_spot', 'Apple___Apple_scab',
                      'Tomato___Late_blight', 'Apple___Black_rot', 'Apple___Cedar_apple_rust',
                      'Apple___healthy', 'Tomato___healthy', 'Strawberry___healthy',]


# distribution: list of lists
#     Define distribution of images for each worker training subsets for each of
#     the included categories.
# test_split: float
#     Define the proportion of images going in the test set.
# val_split: float
#     Define the proportion of images going in the validation set.
# max_size: int
#     The maximal number of images retained for a category.
distributions: [[0, 0.5, 0.1, 0.5, 0.1, 0.6, 0.2, 0.2, 0],
                [0, 0.2,  0.7, 0.3, 0.3, 0, 0.35, 0.25, 0],
                [0.2, 0.2, 0.2, 0, 0.6, 0.4, 0.3, 0.3, 0.3],
                [0.8, 0.1, 0, 0.2, 0, 0, 0.15, 0.25, 0.7]]
test_split: 0.1
val_split: 0.15
max_size: 1200

# Hyperarameters for training the model and number of workers.
batch_size: 16
test_batch_size: 16
epochs: 20
lr: 0.001
gamma: 0.7
seed: 1
log_interval: 10
save_model: False
batches_per_iter: 10 # Number of batches per worker training iteration
num_classes: 9 # Number of classes
checkpoint_path: /home/ubuntu/code/FederatedLearningDemo/checkpoints/trained_mobilenetv2.pt
training_stats_path:  /home/ubuntu/code/FederatedLearningDemo/checkpoints/training_stats.csv
update_lim: 4 # Number of workers requested
